### ISSUE TITLE
Feature: load global variables as an object / string

### ISSUE THREAD

**Issue by wswebcreation** [mdasberg/ng-apimock#14]
**Current:**
We now need to add each global variable per key (for local development and also for protractor tests)

**Desired situation:**
It would be nice if we can add global variables as an object / string like this

```js
[{
    name: 'key1', 
    value: '1'
}, {
    name: 'key2',
    value: '2'
}]

// or
key1::'1'::key2::'2'
```

**Comment by mdasberg** [comment]
just release v1.4.0 which contains this feature
