### ISSUE TITLE
Feature: ng-apimock watches changes in mockdata

### ISSUE THREAD

**Issue by wswebcreation** [mdasberg/ng-apimock#16]
**Current:**
When mockdata is changed ng-apimock needs to be reloaded and looses it's state / global variables

**Desired situation:**
It would be nice that there is a watcher in ng-apimock that watches the mockdata-folder and keeps the selected scenario's / global variables that already been loaded.

**Comment by bastiannijboer** [comment]
+1. This would also help us a lot!

**Comment by wswebcreation** [comment]
Awesome!!

**Comment by mdasberg** [comment]
just release v1.4.0 which contains this feature

**Comment by bastiannijboer** [comment]
Great!!

**Comment by wswebcreation** [comment]
And it works like a charm!! Tnx

**Comment by bastiannijboer** [comment]
Also tried it now and works nicely! Thanks a lot.
