### ISSUE TITLE
Examples for angular2+ and protractor

### ISSUE THREAD

**Issue by ebem** [mdasberg/ng-apimock#18]
Can You please provide some examples for e2e tests using angular2+ and protractor ? 

I tried to do as said in : "Howto use for your protractor tests."
But this throws error:  ngApimock.selectScenario(...) , Cannot find name 'ngApimock'
What am I missing here ?
I added global.ngApimock = require('.. path to: protractor.mock.js') and also did: "Using Angular 2 or higher with Protractor?" steps, but no success. 

Angular 4.0.0
Protractor ~5.1.0

**Comment by wswebcreation** [comment]
Hi @ebem ,

Can you please provide your config file how you implemented it. According to the docs it should be required in the `onPrepare()` method of Protractor

**Comment by Local9** [comment]
Sorry, also some what confused.

I'm using the angular-cli, I have read the example in your comment and tried my best to make it work within this frame work but still not getting it.

I gathered the protractor.mock.js should possibly be;
`var ngApimock = require('ng-apimock')();

ngApimock.run({
  "src": "mocks", 
  // "outputDir": "path/to/outputDir", 
  "done": function() { 
  // async
  }
});

return ngApimock;`

maybe wrong... but as I'm also working within TypeScript it doesn't see the ngApimock in the e2e tests.

**Comment by wswebcreation** [comment]
@ebem 

I saw an email from github that you added more info, but I can't see it here. Did something went wrong?

**Comment by ebem** [comment]
No sorry for my late response. The thing is, I already changed my logic for mockup server in my application, so I can't provide you with the config file, it useless for ng-apimock. I will try this (ng-apimock) package some time in future and will see how it works for my next app and give you a feed back.. So I guess you can close this issue. 

P.S Thanks for your fast response.

**Comment by wswebcreation** [comment]
Ok,

Tnx, I'll close the issue for now
