### ISSUE TITLE
Please add functionality to add a delay by default

### ISSUE THREAD

**Issue by sandervalstar** [mdasberg/ng-apimock#20]
In tests it's possible to set a delay with the delayResponse function, however during development I can only add a delay to a mocked endpoint manually on the /mocking page.
I would like to add a small delay to some endpoints by default so it's easy to see during development that the loading spinners still work.

I would propose an optional **"delay"** or **"delayResponse"** field to the responses like illustrated below.

```json
{
  "expression": "todo\/.*",
  "method": "GET",
  "name": "getTodo",
  "isArray": false,
  "responses": {
    "successful": {
      "default": true,
      "status": 200,
      "delay": 500
    }
  }
}
```

**Comment by wswebcreation** [comment]
Hi @sandervalstar 

Tnx for your suggestion, if you have time for it you may also add a PR for it :)

**Comment by mdasberg** [comment]
@sandervalstar I just implemented the change you suggested. 
When the build is successful, I will create a release.

**Comment by sandervalstar** [comment]
That's awesome! Thanks a lot!

On Jul 10, 2017 23:45, "Mischa Dasberg" <notifications@github.com> wrote:

@sandervalstar <https://github.com/sandervalstar> I just implemented the
change you suggested.
When the build is successful, I will create a release.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mdasberg/ng-apimock/issues/20#issuecomment-314258898>,
or mute the thread

**Comment by mdasberg** [comment]
v1.3.0 has been released

**Comment by sandervalstar** [comment]
Just upgraded and it works, thanks again!
