### ISSUE TITLE
Feature: response based on POST params

### ISSUE THREAD

**Issue by JurajVajda** [mdasberg/ng-apimock#21]
While in GET method we can use regexp for matching url parameters in POST requests is no option of getting different mock response based on the POST request parameters. As a developer and tester i would like to configure mock response based on the POST parameters so i can test interaction with the application and rest api calls.

**Comment by baconcutter** [comment]
+1

**Comment by builtbyjay** [comment]
I would also find this feature very useful :)

**Comment by eyalkenig** [comment]
+1

**Comment by foofighter69** [comment]
+1

**Comment by kc13greiner** [comment]
+1

**Comment by trietsch** [comment]
+1
