### ISSUE TITLE
Improvement: Add baseUrl at run configuration

### ISSUE THREAD

**Issue by victorsoliveira** [mdasberg/ng-apimock#43]
I'm trying to use ngapimock lib, but, geneated protractor-mock.js use "browser.baseUrl"  fixed info and i'm trying to use with my ionic project , but i need the mock server up at different port of my ionic project.

So, if i make a improve at run configuration adding a baseUrl info we can use that at protractor-mock.js, if was null, use browser.baseUrl.

Can i make this improve and send a PR for u ?

Thanks!

**Comment by wswebcreation** [comment]
Hi @victorsoliveira 

That would be awesome. @mdasberg Will you also pick that up in the refactor?

**Comment by mdasberg** [comment]
of course, please do, I will implement it in the rewrite as well

**Comment by victorsoliveira** [comment]
@mdasberg I'm doing now!
Thanks!

**Comment by victorsoliveira** [comment]
@mdasberg PR #44!

**Comment by victorsoliveira** [comment]
@wswebcreation The PR #44 was merged!
@mdasberg waiting for next release!  ;-)

**Comment by mdasberg** [comment]
@victorsoliveira v1.4.5 has been released
