### ISSUE TITLE
Error when updating or re-installing package

### ISSUE THREAD

**Issue by emartinez-usgs** [mdasberg/ng-apimock#45]
Error occurs when upgrading or attempting to re-install package on top of itself. The problem seems to be related to the fact that the `.git` directory is included in the package distribution. Can this be removed?

To reproduce:
```sh
$ npm install ng-apimock
$ npm install ng-apimock
```
Installing the first time seems to work fine, the second install produces the following error:
```
npm ERR! path /foo/node_modules/ng-apimock
npm ERR! code EISGIT
npm ERR! git /foo/node_modules/ng-apimock: Appears to be a git repo or submodule.
npm ERR! git     /foo/node_modules/ng-apimock
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Comment by mdasberg** [comment]
Thank you for reporting this issue. I will make a fix for it.

**Comment by mdasberg** [comment]
version 1.4.6 has been released which fixes this.

**Comment by emartinez-usgs** [comment]
Fix works great. Thank you. 👍
