### ISSUE TITLE
Cannot use the same scenario but different response

### ISSUE THREAD

**Issue by JongchanaP** [mdasberg/ng-apimock#67]
In case API is the same but different in the body in a request.

Is this possible to use ng-Apimock?

Example:
API /api/everything
body request: { "source" : "customer", "id" : "123" }
response: mocks/data/customer.json

API /api/everything
body request: { "source" : "order", "id" : "O0001" }
response: mocks/data/order_o0001.json

**Comment by Local9** [comment]
Yes, by using select `selectScenario` you can change what data is returned from the API.

**Comment by mdasberg** [comment]
@JongchanaP I have rewritten the apimock to https://github.com/ng-apimock/core but haven't updated this github repo yet. 

In the new version you can match request url, method, headers and payload.
This should do what you want. (https://github.com/ng-apimock/core#how-to-write-mocks)
