### ISSUE TITLE
Is it working with Angular 7?

### ISSUE THREAD

**Issue by Zima04** [mdasberg/ng-apimock#72]
So i have a question.Is it support Angular 7? I try to use this lib by your tutorial for angular cli, but it isn't working.

**Comment by Zima04** [comment]
Maybe someone has an example?

**Comment by mdasberg** [comment]
@Zima04 I have been working on a new version in which I have split up ng-apimock.

https://github.com/ng-apimock/core
https://github.com/ng-apimock/protractor-plugin
https://github.com/ng-apimock/dev-interface

and some demo's (https://github.com/ng-apimock/demo)

This version works with Angular 7
