### ISSUE TITLE
record call for live api

### ISSUE THREAD

**Issue by vlad-borsh** [mdasberg/ng-apimock#73]
Can you add documentation for record calls for live api?

**Comment by mdasberg** [comment]
@vlad-borsh each ng-apimock client has the function [recordRequests](https://github.com/ng-apimock/base-client/blob/master/src/client.ts#L54), which enables ng-apimock to record all api calls.

You can get the recordings using the function [getRecordings](https://github.com/ng-apimock/base-client/blob/master/src/client.ts#L41) or through the dev-interface recordings tab
