### ISSUE TITLE
Overlay requests

### ISSUE THREAD

**Issue by Zima04** [mdasberg/ng-apimock#77]
Hello. I have problem. For example, two requests with params :
 first -
  "expression": "/api/projects/1/documents/1/rename",
    "method": "POST"
second - 
"expression": "/api/projects/1/documents",
 "method": "POST"
Waiting behavior that is each of them should get their response.But i have result, that each of them have response from second request.Can you tell me how to resolve this?
Best regards.

**Comment by Zima04** [comment]
I found decision : "^\/Reporting\/api\/projects\/1\/documents$". That was my sick knowledge of regular expressions and patterns :)

**Comment by anandkhatri** [comment]
Hi @Zima04  I'm facing similar issue, could you please share the solution that you have applied? It would be greatly appreciated.
