### ISSUE TITLE
Dependency security vulnerabilities

### ISSUE THREAD

**Issue by timm-unipro** [mdasberg/ng-apimock#78]
Many thanks for the plugin - it's very useful.

NPM Audit is giving a high level warning for lodash
https://nodesecurity.io/advisories/1065

- and a low level warning for braces
https://nodesecurity.io/advisories/786

Could you please update those dependencies.

Much appreciated

**Comment by mdasberg** [comment]
@timm-unipro I will create a new release tonight

**Comment by timm-unipro** [comment]
@mdasberg - any update on this?, thanks

**Comment by mdasberg** [comment]
I just release 1.4.9 which removes all the high level warnings
